# дополнительные ключи props, сохран€емые в SciTE.session

[main]
toolbar.visible = 
tabbar.visible = 
statusbar.visible = 
view.whitespace = 
view.eol = 
view.indentation.guides = 
line.margin.visible = 
split.vertical = 
wrap = 
output.wrap = 
magnification = параметр измен€етс€ в Zoom.lua
output.magnification = параметр измен€етс€ в Zoom.lua
print.magnification = параметр измен€етс€ в Zoom.lua
sidebar.show = параметр измен€етс€ в SideBar.lua
sidebar.active.tab = параметр измен€етс€ в SideBar.lua
sidebar.position = 'left' or 'right' if sidebar as panel
sidebar.win = panel or window mode
output.code.page = 
sidebar.posx = X position sidebar in window mode
sidebar.posy = Y position sidebar in window mode
highlighting.identical.text  = параметр измен€етс€ в highlighting_identical_text.lua
font.set = индекс набора шрифтов в FontChanger.lua
