# Define SciTE settings for UNBOUND2 files.

file.patterns.unbound=*.unbound
filter.unbound=Unbound (unbound)|$(file.patterns.unbound)|

*filter.unbound=$(filter.unbound)

lexer.$(file.patterns.unbound)=script_unbound
*language.unbound=Unbound|unbound||

# top level methods
keywords.$(file.patterns.unbound)=var bind style element event block def controller macro args renderer \
class scope bindcall tf struct constant trigger dispatch hblock tr extends css layout content scrollArea \
filters exprs htile vtile mc controllerEvents symbol dropShadow sprite sync reverse hreverse

# props
keywords2.$(file.patterns.unbound)=x y width enabled alpha text name height value visible align to watch \
duration position marginTop id backgroundImage marginBottom play backgroundColor on action init count top \
hitTest delay from easing marginRight marginLeft left right visualOffsetY backgroundSize paddingRight \
paddingLeft bottom flow paddingTop textColor colorTransform paddingBottom scaleY items scaleX borderRadius \
leading textAlign color padding vgap maxWidth hgap scale9grid fontSize offset backgroundPath rotation arc \
gap pivotX pivotY radius effectPath visualScaleY isMask ubScaleY marginTextTop visualScaleX visualOffsetX \
itemHeight marginTextLeft marginTextBottom marginTextRight angle quality wordWrap itemOffset maxHeight \
priority ubScaleX itemWidth minHeight tooltipType repeatController innerRadius borderRadiusBottomRight \
multiline lineThickness fontFamily elideMode screenBoundsOffset minWidth scrollPerItem onEndedEvent htmlText \
margin borderRadiusBottomLeft effectColor noTranslate styleSheet distance blurY blurX lineAlpha hcenter \
borderRadiusTopRight skin borderRadiusTopLeft letterSpacing offsetMap strength hideAnimation zindex pause \
hideOnMove alphas ratios scrollDuration lineColor colors resume hideOnEsc mouseEnabled backgroundRepeatX \
gripType reuseElement matrix mergeLayers colorMatrix mouseChildren sharedCache antiAliasType orientation \
doubleClickEnabled selectable onStartedEvent hscrollPolicy gripMask backgroundRepeatY cache vcenter vscrollPolicy \
outlineColor outlineAlpha outlineThickness dashLength spacing keyframes tabIndex defaultFocus clickFocus \
clickInterval autoSize showAnimation repeatCount

# data types
keywords3.$(file.patterns.unbound)=bool number str dhComponent dhEntity dict array gfx dhCollection expression

# boolean literals
keywords4.$(file.patterns.unbound)=false true

comment.block.script_unbound=#

# unbound styles
# Default
style.script_unbound.0=fore:#000000
# Comment
style.script_unbound.1=fore:#808000
# Operators
style.script_unbound.2=$(colour.operator)
# Literal string
style.script_unbound.3=$(colour.comment)
# Number
style.script_unbound.4=$(colour.number)
# Data types
style.script_unbound.5=fore:#0080C0,italics
# $Controllers
style.script_unbound.6=fore:#800800
# Keyword
style.script_unbound.7=$(colour.keyword)
# Keywords2
style.script_unbound.8=fore:#0080C0
# Keywords4
style.script_unbound.9=fore:#000088

# Сворачивание блоков
fold.script_unbound=1

# Подключение файлов сокращений
abbreviations.$(file.patterns.unbound)=$(SciteDefaultHome)\abbrev\unbound.abbrev